properties:
  first:
    $ref: './Href.yaml'
  last:
    $ref: './Href.yaml'
  next:
    $ref: './Href.yaml'
  previous:
    $ref: './Href.yaml'
  self:
    $ref: './Href.yaml'
  total:
    type: integer
type: object
